name: Build and Release Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: 1.1.1  # Starting version, update as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "latest"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --build-name=$VERSION --build-number=$GITHUB_RUN_NUMBER

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "FarmHelp Android v${{ env.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          asset_path: ./build/app/outputs/flutter-apk/app-release.apk
          asset_name: FarmHelp-v${{ env.VERSION }}.apk
          asset_content_type: application/vnd.android.package-archive
